spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_social_network
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: localhost
    port: 1025
    username: shubham
    password: shubham
    protocol:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
application:
  security:
    jwt:
      SECRET_KEY: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      EXPIRATION_TIME: 864000000 # 1 days
  mailing:
    frontend:
      activation-url: http://localhost:8080/activate
  file:
    upload:
      photos-output-path: ./uploads
server:
    port: 8088

